// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pkg/proto/anidb.proto

package dbservice

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NewEntries int32  `protobuf:"varint,2,opt,name=newEntries,proto3" json:"newEntries,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_anidb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_anidb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pkg_proto_anidb_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Result) GetNewEntries() int32 {
	if x != nil {
		return x.NewEntries
	}
	return 0
}

//
//List of episodes that are to be downloaded.
type EpisodeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Episodes []*AnimeDetails `protobuf:"bytes,1,rep,name=episodes,proto3" json:"episodes,omitempty"`
}

func (x *EpisodeList) Reset() {
	*x = EpisodeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_anidb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EpisodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeList) ProtoMessage() {}

func (x *EpisodeList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_anidb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeList.ProtoReflect.Descriptor instead.
func (*EpisodeList) Descriptor() ([]byte, []int) {
	return file_pkg_proto_anidb_proto_rawDescGZIP(), []int{1}
}

func (x *EpisodeList) GetEpisodes() []*AnimeDetails {
	if x != nil {
		return x.Episodes
	}
	return nil
}

//*
// Details related to downloading an episode of any given anime.
type AnimeDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeName    string `protobuf:"bytes,1,opt,name=animeName,proto3" json:"animeName,omitempty"`
	SeasonNumber int32  `protobuf:"varint,2,opt,name=seasonNumber,proto3" json:"seasonNumber,omitempty"`
	Episode      int32  `protobuf:"varint,3,opt,name=episode,proto3" json:"episode,omitempty"`
	MagnetLink   string `protobuf:"bytes,4,opt,name=magnetLink,proto3" json:"magnetLink,omitempty"`
	AnimeID      int32  `protobuf:"varint,5,opt,name=animeID,proto3" json:"animeID,omitempty"`
	Quality      string `protobuf:"bytes,20,opt,name=quality,proto3" json:"quality,omitempty"`
}

func (x *AnimeDetails) Reset() {
	*x = AnimeDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_anidb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeDetails) ProtoMessage() {}

func (x *AnimeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_anidb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeDetails.ProtoReflect.Descriptor instead.
func (*AnimeDetails) Descriptor() ([]byte, []int) {
	return file_pkg_proto_anidb_proto_rawDescGZIP(), []int{2}
}

func (x *AnimeDetails) GetAnimeName() string {
	if x != nil {
		return x.AnimeName
	}
	return ""
}

func (x *AnimeDetails) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *AnimeDetails) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

func (x *AnimeDetails) GetMagnetLink() string {
	if x != nil {
		return x.MagnetLink
	}
	return ""
}

func (x *AnimeDetails) GetAnimeID() int32 {
	if x != nil {
		return x.AnimeID
	}
	return 0
}

func (x *AnimeDetails) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

type AniParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeID int32  `protobuf:"varint,1,opt,name=animeID,proto3" json:"animeID,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AniParams) Reset() {
	*x = AniParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_anidb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AniParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AniParams) ProtoMessage() {}

func (x *AniParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_anidb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AniParams.ProtoReflect.Descriptor instead.
func (*AniParams) Descriptor() ([]byte, []int) {
	return file_pkg_proto_anidb_proto_rawDescGZIP(), []int{3}
}

func (x *AniParams) GetAnimeID() int32 {
	if x != nil {
		return x.AnimeID
	}
	return 0
}

func (x *AniParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pkg_proto_anidb_proto protoreflect.FileDescriptor

var file_pkg_proto_anidb_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x69, 0x64,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x6e, 0x69, 0x72, 0x73, 0x73, 0x2e,
	0x61, 0x6e, 0x69, 0x64, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x40, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x0b, 0x45, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x6e, 0x69, 0x72, 0x73, 0x73, 0x2e, 0x61,
	0x6e, 0x69, 0x64, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x08, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x73, 0x22, 0xbe, 0x01, 0x0a, 0x0c,
	0x41, 0x6e, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x6e, 0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x67, 0x6e,
	0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61,
	0x67, 0x6e, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x69, 0x6d,
	0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x65,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x14, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x39, 0x0a, 0x09,
	0x41, 0x6e, 0x69, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x69,
	0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d,
	0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x92, 0x02, 0x0a, 0x08, 0x41, 0x6e, 0x69, 0x44,
	0x62, 0x53, 0x76, 0x63, 0x12, 0x3f, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x41, 0x6e, 0x69, 0x6d, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x61, 0x6e, 0x69, 0x72, 0x73, 0x73, 0x2e, 0x61, 0x6e,
	0x69, 0x64, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x14, 0x2e,
	0x61, 0x6e, 0x69, 0x72, 0x73, 0x73, 0x2e, 0x61, 0x6e, 0x69, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x41, 0x6e, 0x69, 0x6d,
	0x65, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x61, 0x6e, 0x69, 0x72, 0x73, 0x73,
	0x2e, 0x61, 0x6e, 0x69, 0x64, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x1a, 0x14, 0x2e, 0x61, 0x6e, 0x69, 0x72, 0x73, 0x73, 0x2e, 0x61, 0x6e, 0x69, 0x64, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0b, 0x46, 0x6f, 0x72, 0x63,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x14, 0x2e, 0x61, 0x6e, 0x69, 0x72, 0x73, 0x73, 0x2e, 0x61, 0x6e, 0x69, 0x64, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x10, 0x46, 0x6f, 0x72, 0x63, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x61, 0x6e,
	0x69, 0x72, 0x73, 0x73, 0x2e, 0x61, 0x6e, 0x69, 0x64, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x1a, 0x14, 0x2e, 0x61, 0x6e, 0x69, 0x72, 0x73, 0x73, 0x2e, 0x61, 0x6e,
	0x69, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d,
	0x72, 0x70, 0x63, 0x2f, 0x64, 0x62, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_anidb_proto_rawDescOnce sync.Once
	file_pkg_proto_anidb_proto_rawDescData = file_pkg_proto_anidb_proto_rawDesc
)

func file_pkg_proto_anidb_proto_rawDescGZIP() []byte {
	file_pkg_proto_anidb_proto_rawDescOnce.Do(func() {
		file_pkg_proto_anidb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_anidb_proto_rawDescData)
	})
	return file_pkg_proto_anidb_proto_rawDescData
}

var file_pkg_proto_anidb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_anidb_proto_goTypes = []interface{}{
	(*Result)(nil),        // 0: anirss.anidb.Result
	(*EpisodeList)(nil),   // 1: anirss.anidb.EpisodeList
	(*AnimeDetails)(nil),  // 2: anirss.anidb.AnimeDetails
	(*AniParams)(nil),     // 3: anirss.anidb.AniParams
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_pkg_proto_anidb_proto_depIdxs = []int32{
	2, // 0: anirss.anidb.EpisodeList.episodes:type_name -> anirss.anidb.AnimeDetails
	3, // 1: anirss.anidb.AniDbSvc.AddAnimeById:input_type -> anirss.anidb.AniParams
	3, // 2: anirss.anidb.AniDbSvc.AddAnimeByName:input_type -> anirss.anidb.AniParams
	4, // 3: anirss.anidb.AniDbSvc.ForceUpdate:input_type -> google.protobuf.Empty
	3, // 4: anirss.anidb.AniDbSvc.ForceUpdateAnime:input_type -> anirss.anidb.AniParams
	0, // 5: anirss.anidb.AniDbSvc.AddAnimeById:output_type -> anirss.anidb.Result
	0, // 6: anirss.anidb.AniDbSvc.AddAnimeByName:output_type -> anirss.anidb.Result
	0, // 7: anirss.anidb.AniDbSvc.ForceUpdate:output_type -> anirss.anidb.Result
	0, // 8: anirss.anidb.AniDbSvc.ForceUpdateAnime:output_type -> anirss.anidb.Result
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_anidb_proto_init() }
func file_pkg_proto_anidb_proto_init() {
	if File_pkg_proto_anidb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_anidb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_anidb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EpisodeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_anidb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimeDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_anidb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AniParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_anidb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_anidb_proto_goTypes,
		DependencyIndexes: file_pkg_proto_anidb_proto_depIdxs,
		MessageInfos:      file_pkg_proto_anidb_proto_msgTypes,
	}.Build()
	File_pkg_proto_anidb_proto = out.File
	file_pkg_proto_anidb_proto_rawDesc = nil
	file_pkg_proto_anidb_proto_goTypes = nil
	file_pkg_proto_anidb_proto_depIdxs = nil
}
